### ISSUE TITLE
Give credit to World Models

### ISSUE THREAD

**Issue by TrentBrick** [sksq96/pytorch-vae#5]
Hey thanks for having this code up. 

However, I have realized that it is almost completely identical to David Ha's World Models research https://arxiv.org/pdf/1803.10122.pdf and code including the code here: https://github.com/ctallec/world-models 

Please give credit where credit is due.

**Comment by sksq96** [comment]
Yes, I was re-implementing David's paper when it was released. I apologize for forgetting to cite his research and would do so in the README. 

As per the code, it's my original implementation and I'm sure [https://github.com/ctallec/world-models](https://github.com/ctallec/world-models) would be similar.
